[manager]
prepend_keymap = [
    { on = [
        "i",
    ], run = "arrow -1", desc = "Move cursor up" },
    { on = [
        "k",
    ], run = "arrow 1", desc = "Move cursor down" },
    { on = [
        "j",
    ], run = "leave", desc = "Go back to the parent directory" },
    { on = [
        "l",
    ], run = "enter", desc = "Enter the child directory" },
    { on = [
        "g",
        "g",
    ], run = "arrow -99999999", desc = "Move cursor to the top" },
    { on = [
        "G",
    ], run = "arrow 99999999", desc = "Move cursor to the bottom" },
    { on = [
        "<A-i>",
    ], run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = [
        "<A-k>",
    ], run = "seek 5", desc = "Seek down 5 units in the preview" },
    { on = [
        "<A-h>",
    ], run = "seek -99999999", desc = "Seek top in the preview" },
    { on = [
        "<A-;>",
    ], run = "seek 99999999", desc = "Seek bottom in the preview" },
]

[select]
prepend_keymap = [
    { on = [
        "i",
    ], run = "arrow -1", desc = "Move cursor up" },
    { on = [
        "k",
    ], run = "arrow 1", desc = "Move cursor down" },
]

[input]
prepend_keymap = [
    { on = [
        "<A-j>",
    ], run = "move -1", desc = "Move cursor left" },
    { on = [
        "<A-l>",
    ], run = "move 1", desc = "Move cursor right" },
]

[help]
prepend_keymap = [
    { on = [
        "i",
    ], run = "arrow -1", desc = "Move cursor up" },
    { on = [
        "k",
    ], run = "arrow 1", desc = "Move cursor down" },
]
