# chrome 安装说明文档
include::../../../doc/base.adoc[]

https://wiki.archlinux.org/title/Chromium[官方文档]



## 问题记录

[#bitwarden-window-tiled]
### 使用 `wayland` 启动后， `Bitwarden` 插件弹框不是浮动

当使用 `xwayland` 启动时， 在页面的密码框输入的时候， `Bitwarden` 插件弹出 "验证身份" 的窗口是浮动的，出现在插件图标的下方。

当使用 `wayland` 启动时， `Bitwarden` 插件弹出 "验证身份" 的窗口是平铺的。

.hyprctl clients 查看窗口信息
[source,console]
----
Window 5f053ae10530 -> Bitwarden:
        mapped: 1
        hidden: 0
        at: 770,225
        size: 380,630
        workspace: 3 (3)
        floating: 1
        pseudo: 0
        monitor: 1
        class: chrome-nngceckbapebfimnlniiiahkandclblb-Default
        title: Bitwarden
        initialClass: chrome-nngceckbapebfimnlniiiahkandclblb-Default
        initialTitle: _crx_nngceckbapebfimnlniiiahkandclblb
        pid: 13150
        xwayland: 0
        pinned: 0
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags:
        swallowing: 0
        focusHistoryID: 2
----

于是我设置 `Hyprland` 的窗口规则让它浮动。

[source]
----
windowrulev2 = float, class: ^chrome.*, title: ^(Bitwarden)$
windowrulev2 = move onscreen cursor 0 0, class: ^chrome.*, title: ^(Bitwarden)$
----

发现并不生效。然后又尝试如下：

[source]
----
# 不行
windowrulev2 = float, title: ^(Bitwarden)$

# 可以
windowrulev2 = float, class: chrome

----

也就是说使用 `title` 匹配不行，怀疑 `title` 在启动初期并不是 `Bitwarden` 。

于是我使用 `while` 循环一直输出 `hyprctl clients` ，去捕捉最初的桌面状态。

[source,console]
----
Window 5f053ae33290 -> _crx_nngceckbapebfimnlniiiahkandclblb:
	mapped: 1
	hidden: 0
	at: 770,225
	size: 380,630
	workspace: 3 (3)
	floating: 1
	pseudo: 0
	monitor: 1
	class: chrome-nngceckbapebfimnlniiiahkandclblb-Default
	title: _crx_nngceckbapebfimnlniiiahkandclblb
	initialClass: chrome-nngceckbapebfimnlniiiahkandclblb-Default
	initialTitle: _crx_nngceckbapebfimnlniiiahkandclblb
	pid: 13150
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 0

----

和我预想的一样。使用下面这个规则就可以了。

[source]
----
windowrulev2 = xxxx, class: ^chrome.*, initialTitle: ^(_crx_.*)$
----

### 切换输入法，输入法状态提示没有出现在光标处

升级 chrome 后出现了这个问题，在输入法切换时，输入法状态提示没有出现在光标处，而是出现在窗口左上角或者左侧边缘中间的位置。

第一次输入出现候选词的位置也是如此，但是继续输入时，候选词会自动出现在光标处。

相关问题记录：

- https://issues.chromium.org/issues/362191728[Wayland text-input-v3: Input window shown at the top-left corner of window first time after input field is focused]
- https://github.com/labwc/labwc/issues/2170[Input in chromuim by text-input-v3, the pop windows will blink one time. ]

[source]
----
--wayland-text-input-v3=disable
----

设置启动项参数 `--wayland-text-input-v3=disable` 并没有生效。

目前是在 `chrome://flags/#wayland-text-input-v3` 手动设置为 `Disabled`。

[.red]#FIXME: 后续持续关注这个问题。#