
[manager]
scrolloffsort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = true


[opener]
# text = [{ run = 'vim "$@"', block = true }]
vscode = [
    { run = 'code "$@"', block = true, for = "linux", desc = "Open With VSCode" },
]

[open]
rules = [
    { mime = "text/*", use = [
        "open",
        "edit",
        "vscode",
    ] },
    { mime = "inode/directory", use = [
        "open",
        "vscode",
    ] },
]


[plugin]
prepend_previewers = [
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]
