# rofi 安装说明文档
include::../../../doc/base.adoc[]

- https://github.com/davatorium/rofi[官方仓库]
- https://github.com/in0ni/rofi-wayland[rofi wayland]
- https://davatorium.github.io/rofi/[官方文档]


## 问题记录

### 原生wayland的支持

目前有一个仓库支持wayland的： https://aur.archlinux.org/packages/rofi-lbonn-wayland-git[rofi-lbonn-wayland-git]

对应的 `Archlinux` 的包是 `rofi-wayland` 。

[#rofi-focus]
### rofi 焦点问题

使用的包是： https://archlinux.org/packages/extra/x86_64/rofi/[rofi]

启动 `rofi` 总是没有焦点，不能直接输入或者选中，需要鼠标移动到它上面才可以

有时候启动 `rofi` 后，输入后界面会跑到另一个显示器上。

有时候启动 `rofi` 后程序的宽度不一样，并且不能输入，鼠标移动上去没反应，也不能点击。

尝试修改Hyprland的窗口规则也不能解决问题：

[source]
----
windowrulev2 = center 1,class:^(Rofi)$
windowrulev2 = stayfocused,class:^(Rofi)$
windowrulev2 = forceinput,class:^(Rofi)$
----

使用 `rofi-wayland` 包后，焦点的问题解决了。应该是 `rofi` 在 `xwayland` 上有问题。

还是期望官方可以早日支持 `wayland` 。

### `'calc.so' does not match`

更新 `rofi` 后运行 `rofi` 失败，在终端运行 `rofi` 报错：`ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007`。

这个是因为使用的是 https://archlinux.org/packages/extra/x86_64/rofi-wayland/[rofi-wayland] 包，而 `rofi-calc` 是官方仓库的包，它是适配官方仓库的 `rofi` 的。

官方仓库的 `rofi` 是不支持 `wayland` 的。

https://github.com/svenstaro/rofi-calc/issues?q=abi+version+of+plugin[rofi-calc] 仓库里可以看到类似的问题。

大部分的提到的解决方式是重新源码编译 `rofi-calc` 包。

但是官方仓库的 `rofi-calc` 是二进制包，所以只能使用 `rofi-calc-git` 包。

后面我发现报这个报错并不是导致 `rofi` 启动失败的原因，这个报错只会导致不能使用 `rofi-calc` 的功能， `rofi` 是可以正常启动的。

[source,console]
====
❯ rofi -show calc -modi calc -no-show-match -no-sort

(process:2443): Rofi-WARNING **: 16:40:34.434: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007
❯ rofi -show-icons -show combi -combi-modes "drun,window,run,ssh" -modes combi

(process:2503): Rofi-WARNING **: 16:41:10.464: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007
====

第一个命令可以运行 `rofi` ，但是提示错误： `Mode calc is not found` 。
第二各命令可以运行 `rofi` ，并且可以运行程序。

安装 `rofi-calc-git` 包后，再次运行 `rofi` 就没有这个报错了。

考虑到我没怎么使用 `rofi-calc` 的功能，所以后面我也就没有部署它。


### rofi 运行异常 `bus error`

[source,console]
====

❯ rofi -show-icons -show combi -combi-modes "drun,window,run,ssh" -modes combi
bus error (core dumped)  rofi -show-icons -show combi -combi-modes "drun,window,run,ssh" -modes combi

====

目前不知道具体原因，重启电脑可以解决。


### `run-shell-command` 配置的说明

这个配置是值通过终端运行命令时运行的方式。

例如通过 `drun` 模式运行 `yazi.desktop` 时，它就是通过 `run-shell-command` 指定的方式运行 `yazi` 命令。

因为 `yazi.desktop` 文件里指定了 `Terminal=true` ，这个是 `desktop` 的规范，它告诉启动器我需要通过终端来运行。

通过分析 `yazi` 源码： `source/modes/drun.c` 和 `source/helper.c::helper_execute_command` 

`rofi` 也是解析 `desktop` 文件里的 `Terminal` 字段来判断的。

- 当 `Terminal=true` 时， `rofi` 会通过 `run-shell-command` 指定的方式来运行命令。
- 当 `Terminal=false` 或者没有指定时， `rofi` 会通过 `run-command` 指定的方式来运行命令。


### `run` 模式下运行 `yazi` 闪退的问题

通过 `run` 模式下运行 `yazi` 程序，会闪退。

运行 `yazi` 命令需要依附终端，直接运行 `yazi` 命令是不可以的，这个不是 `rofi` 的问题。

`rofi` 运行命令的方式是通过 `run-command` 配置来指定的，默认是 "`{cmd}`"，也就是直接运行命令。

我们可以修改 `run-command` 配置为 `wezterm -e {cmd}` 或者 `wezterm start -- {cmd}`，这样就可以运行了。

但是这就导致其他的命令也会通过终端运行，例如 `vscode` ，导致 `rofi` 会先运行终端，终端里再运行 `vscode` ，导致界面会闪一下，就是启动终端的界面会打开再关闭。

[.red]#所以还是不建议修改 `run-command` 配置。#

参考： https://davatorium.github.io/rofi/1.7.3/rofi.1/#run[rofi run模式]里的说明。

我们可以通过 `accept-alt` 快捷键绑定 (默认是 `shift-enter` ) 来通过终端运行命令。


### `combi` 运行 `yazi 目录路径` 闪退的问题

如果设置 `run-command` 配置为 `wezterm start -- {cmd}` 。

在 `combi` 模式下输入 `yazi ~` ,并不会打开 `yazi` ，而是闪退。

这个是因为在 `combi` 模式下，输入的命令是 `yazi ~` ，在候选框里并没有候选项，它并不是运行这个命令，而是直接退出了。

在 `run` 模式下输入 `yazi ~` ,会打开 `yazi` ，因为指定 `run` 模式下它会运行这个命令，即使没有候选项。

[.green]#所以运行命令指定参数时一定要切换到 `run` 模式下运行，不能在 `combi` 模式下运行。#

[.red]#上面测试都是建立在修改 `run-command` 配置为 `wezterm start -- {cmd}` 的情况下。#


