
# https://explosion-mental.codeberg.page/wallust/intro.html

alpha = 80
backend = "full"
color_space = "lab"
filter = "softdarkcomp16"

[templates]

hyprlock = { template = 'hyprlock.conf', target = '~/.cache/colors/hyprlock.conf' }

wlogout = { template = 'wlogout.css', target = '~/.cache/colors/wlogout.css' }

rofi = { template = 'rofi.rasi', target = '~/.cache/colors/rofi.rasi' }

zsh = { template = 'zsh.zsh', target = '~/.cache/colors/zsh.zsh' }

wezterm = { template = 'wezterm_colors.lua', target = '~/.cache/colors/wezterm_colors.lua' }

swaync = { template = 'swaync.css', target = '~/.cache/colors/swaync.css' }

hyprland = { template = 'hyprland.conf', target = '~/.cache/colors/hyprland.conf' }
